# Generated by Django 4.2.13 on 2024-06-15 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfPomodoro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pomodoro_time', models.IntegerField(default=25)),
                ('pomodoro_short_break', models.IntegerField(default=5)),
                ('pomodoro_long_break', models.IntegerField(default=10)),
                ('counts_short_breaks', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Pomodoro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Активная', 'Active'), ('Завершена', 'Done'), ('Пауза', 'Paused')], default='Активная', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_manager_app.task')),
                ('type_of_pomodoro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_manager_app.typeofpomodoro')),
            ],
        ),
    ]
