# Generated by Django 4.2.13 on 2024-06-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neuron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('weight', models.FloatField()),
                ('step_amount', models.FloatField()),
                ('goal_prediction', models.FloatField()),
                ('number_of_iterations', models.IntegerField()),
                ('version', models.CharField(choices=[('1', 'V1')], default='1', max_length=20)),
            ],
        ),
    ]
