# Generated by Django 4.2.13 on 2024-06-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_neuro_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neuron',
            name='alpha',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='neuron',
            name='version',
            field=models.CharField(choices=[('1', 'V1'), ('2', 'V2')], default='1', max_length=20),
        ),
    ]
