# Generated by Django 4.2.13 on 2024-06-17 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('weights', models.BinaryField()),
                ('alpha', models.FloatField(default=1)),
                ('number_of_iterations', models.IntegerField(default=1)),
                ('next_layer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_layers', to='first_neural_network_app.layer')),
            ],
        ),
    ]
