# Generated by Django 4.2.13 on 2024-06-21 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_neural_network_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='number_of_iterations',
        ),
        migrations.AddField(
            model_name='layer',
            name='last_dropout_mask',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='previous_layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_next_layers', to='first_neural_network_app.layer'),
        ),
        migrations.AddField(
            model_name='layer',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='layer',
            name='type_fn_activation',
            field=models.CharField(choices=[('none', 'None'), ('relu', 'ReLU'), ('sigmoid', 'Sigmoid'), ('tanh', 'Tanh')], default='relu', max_length=255),
        ),
        migrations.AddField(
            model_name='layer',
            name='use_dropout',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='layer',
            name='next_layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_previous_layers', to='first_neural_network_app.layer'),
        ),
        migrations.CreateModel(
            name='NeuroNet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number_of_layers', models.IntegerField()),
                ('first_layer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_layer', to='first_neural_network_app.layer')),
                ('last_layer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_layer', to='first_neural_network_app.layer')),
            ],
        ),
    ]
